In [2]:

import numpy as np


# Numpy Pratice Task

### Create array and find the dimentions

In [ ]:
array1d = np.array([1,2,3,4,5])
array1d



In [ ]:
array1d.ndim

### Summission Of Array

In [ ]:
d = array1d + array1d
d

In [ ]:
d/4

### Create three dimension array( note: one square bracket has one dimension)

In [ ]:
a = np.array([[[1,2,3,4,5]]])
a

In [ ]:
a.ndim

### Numpy arange function

In [ ]:
b = np.arange(20)
b

In [ ]:
c = np.arange(5,8)
c

### Zeros, ones, identity, => np.identity(6)

In [ ]:
d = np.zeros(6)
d

In [ ]:
e = np.identity(6)
e

In [ ]:
f = np.ones(6)
f

### numpy array matrices

In [ ]:
g = np.array([[1,2,3,4,5],[4,5,6,7,8],[1,2,3,4,5]])
g

In [ ]:
e = np.ones_like(g)
e

### arange and reshape function

In [ ]:
f = np.arange(100).reshape(10,10)
f

### m.flatten() function

In [ ]:
h = f.flatten()
h

### (x) find the individual number of elements in a array

In [ ]:
h[8]

In [ ]:
f[1]

In [ ]:
f[1,4]

### (xi) example arra2d > 8

In [ ]:
g = f > 8
g

In [ ]:
h[(h > 5) & (h%2 == 0)]

In [ ]:
k = np.random.randint(10 , size = (10,8))
k

In [ ]:
k[0:1 , 0:] = k[9:10, 0:] = k[0:, 0:1] = k[0:, 7:8] = 0
k

In [3]:
i = np.random.randint(10, size = (9,8))
i

array([[0, 9, 1, 2, 9, 1, 2, 4],
       [8, 3, 4, 6, 7, 8, 9, 1],
       [9, 3, 5, 6, 2, 2, 4, 3],
       [4, 7, 6, 8, 9, 1, 9, 9],
       [5, 9, 7, 7, 6, 1, 5, 6],
       [3, 4, 9, 9, 9, 5, 1, 2],
       [0, 9, 6, 8, 5, 1, 5, 7],
       [4, 2, 4, 6, 4, 9, 6, 3],
       [7, 5, 9, 7, 4, 5, 0, 6]])

In [4]:
i[0:1 , :] = i[8:9, :] = i[: , 0:1] = i[:, 7:8] = 0
i

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 3, 4, 6, 7, 8, 9, 0],
       [0, 3, 5, 6, 2, 2, 4, 0],
       [0, 7, 6, 8, 9, 1, 9, 0],
       [0, 9, 7, 7, 6, 1, 5, 0],
       [0, 4, 9, 9, 9, 5, 1, 0],
       [0, 9, 6, 8, 5, 1, 5, 0],
       [0, 2, 4, 6, 4, 9, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

## Array Attributes

In [10]:
a = np.arange(8).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [12]:
a.ndim

3

In [13]:
print(a.shape)

(2, 2, 2)


In [14]:
# itemsize how many bytes a single value occupied
a.itemsize

4

In [15]:
# dtype or data type 
print(a.dtype)

int32


In [18]:
## array function
b = np.random.random((3,5))
b

array([[0.65272472, 0.45632824, 0.19766125, 0.51164453, 0.49579573],
       [0.75818662, 0.34558923, 0.32474279, 0.60567247, 0.17952328],
       [0.77074375, 0.52839243, 0.42433611, 0.40425653, 0.27826263]])

In [21]:
c = np.random.randint(15, size = (3,5))
c

array([[11, 12, 14,  8,  7],
       [ 5,  4,  4,  7,  2],
       [ 4,  8, 10,  9,  4]])

In [30]:
# max/min/sum/prod
# 0 -> col and 1 -> row
d = np.prod(c, axis = 0)
d
np.max(c, axis = 0)
np.min(c, axis = 0)
np.sum(c, axis = 0)

array([20, 24, 28, 24, 13])

In [25]:
# mean/median/std/var
e = np.var(c, axis = 1)
e

array([6.64, 2.64, 6.4 ])

In [31]:
e = np.std(c, axis = 0)
e
np.mean(c, axis = 1)

array([10.4,  4.4,  7. ])

In [32]:
# Trignometric Function
np.sin(c)

array([[-0.99999021, -0.53657292,  0.99060736,  0.98935825,  0.6569866 ],
       [-0.95892427, -0.7568025 , -0.7568025 ,  0.6569866 ,  0.90929743],
       [-0.7568025 ,  0.98935825, -0.54402111,  0.41211849, -0.7568025 ]])

In [36]:
## Dot Product
a = np.arange(20).reshape(4,5)
b = np.arange(25).reshape(5,5)
np.dot(a,b)

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240]])

## log and Exponent

In [37]:
np.log(c)

array([[2.39789527, 2.48490665, 2.63905733, 2.07944154, 1.94591015],
       [1.60943791, 1.38629436, 1.38629436, 1.94591015, 0.69314718],
       [1.38629436, 2.07944154, 2.30258509, 2.19722458, 1.38629436]])

In [38]:
np.exp(c)

array([[5.98741417e+04, 1.62754791e+05, 1.20260428e+06, 2.98095799e+03,
        1.09663316e+03],
       [1.48413159e+02, 5.45981500e+01, 5.45981500e+01, 1.09663316e+03,
        7.38905610e+00],
       [5.45981500e+01, 2.98095799e+03, 2.20264658e+04, 8.10308393e+03,
        5.45981500e+01]])

## iteration

In [41]:
for i in c:
    print(i)


[11 12 14  8  7]
[5 4 4 7 2]
[ 4  8 10  9  4]


## Transpose

In [42]:
np.transpose(c)

array([[11,  5,  4],
       [12,  4,  8],
       [14,  4, 10],
       [ 8,  7,  9],
       [ 7,  2,  4]])

In [43]:
# ravel and flaten are both same
c.ravel()

array([11, 12, 14,  8,  7,  5,  4,  4,  7,  2,  4,  8, 10,  9,  4])

## Horizontal and Vertical Stacking

In [48]:
a = np.random.randint(30, size = (5,6))
b = np.random.randint(45, size = (5,9))

np.hstack((a,b))

array([[ 2, 25, 28, 27, 14,  2, 22,  2, 15, 16, 10, 33, 34, 30, 37],
       [13, 20,  7,  4, 20,  1,  1,  8, 17, 26, 20,  0, 27,  6, 40],
       [ 0, 22, 13, 22, 14, 16,  1,  2, 44, 17, 34, 30, 41, 17,  3],
       [ 8, 23, 15, 13,  6, 15, 20, 44,  2, 37, 10, 15,  5, 38, 12],
       [14,  8, 17,  4, 26, 28, 27, 21, 24, 33, 14, 17,  1, 18, 34]])

In [49]:
a = np.random.randint(30, size = (5,6))
b = np.random.randint(45, size = (5,9))
np.vstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 1 has size 9

In [51]:
a

array([[ 2, 25, 28, 27, 14,  2],
       [13, 20,  7,  4, 20,  1],
       [ 0, 22, 13, 22, 14, 16],
       [ 8, 23, 15, 13,  6, 15],
       [14,  8, 17,  4, 26, 28]])

## Horizontal and Vertical Spliting

In [60]:
np.hsplit(a,3)

[array([[ 2, 25],
        [13, 20],
        [ 0, 22],
        [ 8, 23],
        [14,  8]]),
 array([[28, 27],
        [ 7,  4],
        [13, 22],
        [15, 13],
        [17,  4]]),
 array([[14,  2],
        [20,  1],
        [14, 16],
        [ 6, 15],
        [26, 28]])]

In [55]:
np.vsplit(a,5)

[array([[ 2, 25, 28, 27, 14,  2]]),
 array([[13, 20,  7,  4, 20,  1]]),
 array([[ 0, 22, 13, 22, 14, 16]]),
 array([[ 8, 23, 15, 13,  6, 15]]),
 array([[14,  8, 17,  4, 26, 28]])]

## Memory

In [63]:
import sys
sys.getsizeof(a)

248

## Find alll numbers greater than 50 and also find the even numbers 

In [64]:
a[a>15]

array([25, 28, 27, 20, 20, 22, 22, 16, 23, 17, 26, 28])

In [66]:
a[ a%2 == 0]

array([ 2, 28, 14,  2, 20,  4, 20,  0, 22, 22, 14, 16,  8,  6, 14,  8,  4,
       26, 28])

In [67]:
# find the numbes divisible and not divisible by 7
a[ a%7 == 0]

array([28, 14,  7,  0, 14, 14, 28])

In [68]:
a[~(a%7 == 0)]

array([ 2, 25, 27,  2, 13, 20,  4, 20,  1, 22, 13, 22, 16,  8, 23, 15, 13,
        6, 15,  8, 17,  4, 26])

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [70]:
# Matrix multiplication if shapes are different
a = np.arange(12).reshape(4,3)
b = np.arange(12,24).reshape(3,4)
#print(a)
#print(b)
# a * b
print(a@b)

[[ 56  59  62  65]
 [200 212 224 236]
 [344 365 386 407]
 [488 518 548 578]]


In [71]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [72]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [74]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]
