In [1]:
import pandas as pd
import numpy as np

# Pandas Series

In [2]:
alist = [11,22,33,44,55,66,88]
alist

[11, 22, 33, 44, 55, 66, 88]

In [3]:
type(alist)

list

In [4]:
nparray = np.array(alist)
nparray

array([11, 22, 33, 44, 55, 66, 88])

In [5]:
type(nparray)

numpy.ndarray

In [6]:
nparray.ndim

1

In [7]:
nparray.shape

(7,)

In [8]:
arr2d = np.arange(5).reshape(5,1)
arr2d

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [9]:
arr2d.shape

(5, 1)

# Pandas Series

In [10]:
PSeries = pd.Series(alist)
PSeries

0    11
1    22
2    33
3    44
4    55
5    66
6    88
dtype: int64

In [11]:
PSeries.index

RangeIndex(start=0, stop=7, step=1)

In [12]:
PSeries.values

array([11, 22, 33, 44, 55, 66, 88], dtype=int64)

In [13]:
PSeries.size

7

In [14]:
S2 = pd.Series([1,2,3,4,5], index = ["Muhammad", "Amin", "Qasim", "Nasir", "Faiz"])
S2

Muhammad    1
Amin        2
Qasim       3
Nasir       4
Faiz        5
dtype: int64

In [15]:
S2["Nasir"]

4

In [16]:
S2 = pd.Series([1,2,3,4,5])
S2

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [17]:
S2[0:2]

0    1
1    2
dtype: int64

In [18]:
S3 = PSeries + S2
S3

0    12.0
1    24.0
2    36.0
3    48.0
4    60.0
5     NaN
6     NaN
dtype: float64

In [19]:
S4 = S3[~np.isnan(S3)]
S4

0    12.0
1    24.0
2    36.0
3    48.0
4    60.0
dtype: float64

In [20]:
S5 = S4.append(S3)

C:\Users\mu.amin\AppData\Local\Temp\ipykernel_16336\322549569.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  S5 = S4.append(S3)


In [21]:
# argmax command is used to show bottom value
S3.argmax()

4

In [22]:
S3.count()

5

In [23]:
S3[(S3>24) & (S3<60)]

2    36.0
3    48.0
dtype: float64

# Pandas Data Frame

In [24]:
data = { "name": ["Muhammad", "Amin", "Qasim", "Faraz", "Danial"], "Father_name": ["Qasim", "name", "Gender","Bluetooth","Bottle"],
       "äge": [1,2,3,4,5,]}
S6 = pd.DataFrame(data)
S6

name Father_name  äge
0  Muhammad       Qasim    1
1      Amin        name    2
2     Qasim      Gender    3
3     Faraz   Bluetooth    4
4    Danial      Bottle    5

In [25]:
# Adding a new column
S6["Gender"] = ["Male","Male","Male","Male","Male"]
S6

name Father_name  äge Gender
0  Muhammad       Qasim    1   Male
1      Amin        name    2   Male
2     Qasim      Gender    3   Male
3     Faraz   Bluetooth    4   Male
4    Danial      Bottle    5   Male

In [26]:
# Delete column
del S6["Father_name"]
S6


name  äge Gender
0  Muhammad    1   Male
1      Amin    2   Male
2     Qasim    3   Male
3     Faraz    4   Male
4    Danial    5   Male

In [27]:
S6["Arrange"]  = np.arange(5)
S6

name  äge Gender  Arrange
0  Muhammad    1   Male        0
1      Amin    2   Male        1
2     Qasim    3   Male        2
3     Faraz    4   Male        3
4    Danial    5   Male        4

In [28]:
S6["Arrange"]

0    0
1    1
2    2
3    3
4    4
Name: Arrange, dtype: int32

In [29]:
S6.iloc[0:2, 0:2]

name  äge
0  Muhammad    1
1      Amin    2

In [30]:
# For particular element in a array matrix 
S6[S6["Gender"] == "Female"]

Empty DataFrame
Columns: [name, äge, Gender, Arrange]
Index: []

In [31]:
# Modify the structure and content of Data Frame
S6

name  äge Gender  Arrange
0  Muhammad    1   Male        0
1      Amin    2   Male        1
2     Qasim    3   Male        2
3     Faraz    4   Male        3
4    Danial    5   Male        4

In [32]:
S6.columns = ["Age","gender", "arrange"]
S6

ValueError: Length mismatch: Expected axis has 4 elements, new values have 3 elements

In [33]:
S6.rename(columns = {"gender": "Male/ Female"}, inplace = True )
S6

name  äge Gender  Arrange
0  Muhammad    1   Male        0
1      Amin    2   Male        1
2     Qasim    3   Male        2
3     Faraz    4   Male        3
4    Danial    5   Male        4

In [34]:
df1 = pd.DataFrame({'course':["DS","DS","DS","DS","DS","DS","DS"], 
                   'time':['7-10','6-10','5-10','6-10','5-10','5-10','7-10']})


df2 =  pd.DataFrame({'height':[5.5,3],'name':["Yair", 'Hassan'], 'age':[34,30]})

In [35]:
df5 = pd.concat((df1,df2), axis = 0)
df5

course  time  height    name   age
0     DS  7-10     NaN     NaN   NaN
1     DS  6-10     NaN     NaN   NaN
2     DS  5-10     NaN     NaN   NaN
3     DS  6-10     NaN     NaN   NaN
4     DS  5-10     NaN     NaN   NaN
5     DS  5-10     NaN     NaN   NaN
6     DS  7-10     NaN     NaN   NaN
0    NaN   NaN     5.5    Yair  34.0
1    NaN   NaN     3.0  Hassan  30.0

In [36]:
df6 = pd.concat((df1,df2), axis = 1)
df6

course  time  height    name   age
0     DS  7-10     5.5    Yair  34.0
1     DS  6-10     3.0  Hassan  30.0
2     DS  5-10     NaN     NaN   NaN
3     DS  6-10     NaN     NaN   NaN
4     DS  5-10     NaN     NaN   NaN
5     DS  5-10     NaN     NaN   NaN
6     DS  7-10     NaN     NaN   NaN

# Removing Rows
Removing rows from a DataFrame object is normally performed using one of

three techniques:

• Using the .drop() method

• Boolean selection

• Selection using a slice

In [39]:
df7 = df6.drop(["name","age"], axis = 1)
df7

course  time  height
0     DS  7-10     5.5
1     DS  6-10     3.0
2     DS  5-10     NaN
3     DS  6-10     NaN
4     DS  5-10     NaN
5     DS  5-10     NaN
6     DS  7-10     NaN

In [40]:
df6.drop([4,5,6],axis=0)

course  time  height    name   age
0     DS  7-10     5.5    Yair  34.0
1     DS  6-10     3.0  Hassan  30.0
2     DS  5-10     NaN     NaN   NaN
3     DS  6-10     NaN     NaN   NaN

In [44]:
df6.reset_index(drop= True, inplace = True )
df6

course  time  height    name   age
0     DS  7-10     5.5    Yair  34.0
1     DS  6-10     3.0  Hassan  30.0
2     DS  5-10     NaN     NaN   NaN
3     DS  6-10     NaN     NaN   NaN
4     DS  5-10     NaN     NaN   NaN
5     DS  5-10     NaN     NaN   NaN
6     DS  7-10     NaN     NaN   NaN

In [50]:
# Remove the specific row by using the ielement value
df6[~(df6["time"]=="7-10")]

course  time  height    name   age
1     DS  6-10     3.0  Hassan  30.0
2     DS  5-10     NaN     NaN   NaN
3     DS  6-10     NaN     NaN   NaN
4     DS  5-10     NaN     NaN   NaN
5     DS  5-10     NaN     NaN   NaN

In [52]:
# find the specific row and column
df6.iloc[[3,5]][['age', 'time']]

age  time
3  NaN  6-10
5  NaN  5-10